# .github/workflows/sync_articles.yml

name: Sync Readwise Articles to Capacities

on:
  # Allow manual triggering of the workflow
  workflow_dispatch:
  # Optionally, you could also add a schedule
  schedule:
     - cron: '0 */12 * * *'  # Runs every 12 hours

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Create empty processed_ids file if it doesn't exist
        run: touch processed_ids.txt
      
      - name: Run sync script
        env:
          READWISE_TOKEN: ${{ secrets.READWISE_TOKEN }}
          CAPACITIES_TOKEN: ${{ secrets.CAPACITIES_TOKEN }}
          CAPACITIES_SPACE_ID: ${{ secrets.CAPACITIES_SPACE_ID }}
        run: python main.py
      
      - name: Commit and push if processed_ids.txt changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add processed_ids.txt
          git diff --quiet && git diff --staged --quiet || git commit -m "Update processed articles list"
          git push